name: Lint Code Base

on: # to run on push and not on PR
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**.html'
      - '**.css'
      - '**.yml'
      - '**.yaml'
      - 'Dockerfile'
  pull_request:
    branches-ignore: [main]

permissions: {}

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v8 # using major version only
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true  
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}