  name: Build and Scan with Trivy

  on:
    workflow_run:
      workflows: ["OWASP Dependency-Check"]
      types: [completed]
    workflow_dispatch: {}   # optional manual trigger for testing

  jobs:
    debug:
      runs-on: ubuntu-latest
      steps:
        - name: Debug workflow_run event
          run: |
            echo "Event name: ${{ github.event_name }}"
            echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
            echo "Workflow run name: ${{ github.event.workflow_run.name }}"
            echo "Workflow run status: ${{ github.event.workflow_run.status }}"


    build_scan_push:
      # Only run this job if the previous workflow (OWASP Dependency-Check) was successful
      if: |
        github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success' ||
        github.event.workflow_run.conclusion == 'skipped'
      runs-on: ubuntu-latest
    
      
      permissions:
        contents: read
        packages: write

      env:
        IMAGE_NAME: coffee-app  # fixed: lowercase, no spaces

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 2

        - name: Set lowercase registry, short SHA, and SemVer
          run: |
            REGISTRY=$(echo "ghcr.io/${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
            SHORT_SHA=${GITHUB_SHA:0:7}
            SEMVER="1.0.${{ github.run_number }}"
            echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
            echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
            echo "SEMVER=$SEMVER" >> $GITHUB_ENV

        - name: Build Docker image
          run: |
            echo "Building Docker image..."
            docker build \
              -t "$REGISTRY/$IMAGE_NAME:$SHORT_SHA" \
              -t "$REGISTRY/$IMAGE_NAME:$SEMVER" \
              -t "$REGISTRY/$IMAGE_NAME:latest" \
              ./app
            echo "Built: $REGISTRY/$IMAGE_NAME:$SHORT_SHA"
            echo "Built: $REGISTRY/$IMAGE_NAME:$SEMVER"
            echo "Built: $REGISTRY/$IMAGE_NAME:latest"

        - name: Run Trivy scan
          if: steps.check_changes.outputs.changes_detected == 'true'   # scan only when app changed / image built
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            format: table
            exit-code: 1
            severity: 'CRITICAL,HIGH'

        - name: Log in to GitHub Container Registry
          if: steps.check_changes.outputs.changes_detected == 'true'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push Docker image to GHCR
          if: steps.check_changes.outputs.changes_detected == 'true'
          run: |
            echo "Pushing images to GHCR..."
            docker push "$REGISTRY/$IMAGE_NAME:$SHORT_SHA"
            docker push "$REGISTRY/$IMAGE_NAME:$SEMVER"
            docker push "$REGISTRY/$IMAGE_NAME:latest"
            echo "Images pushed: $REGISTRY/$IMAGE_NAME"

        - name: Notify - Push skipped
          if: steps.check_changes.outputs.changes_detected == 'false'
          run: |
            echo "Docker image was built/scanned but NOT pushed to GHCR — no changes in ./app"
