name: SonarCloud scan

on:
  workflow_run:
    workflows: ["Superlinter"]
    types:
      - completed
# I no longer want it to run on push, but to wait for call of success or completion from Superlinter ci

jobs:
  sonar-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}    
    # This should depend on the success signal of the Superlinter
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history helps Sonar compute metrics


          # Only want sonar to scan if there are changes
      - name: Check if app code changed
        id: check_changes
        run: |
          # If there is no parent commit (first commit) treat as changed
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            if git diff --quiet HEAD^ HEAD -- ./app; then
              echo "No changes detected in ./app"
              echo "changes_detected=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected in ./app"
              echo "changes_detected=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No parent commit found — treating as changed"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi            
      
      - name: Debug - Check directory structure
        run: |
              echo "Current directory:"
              pwd
              echo ""
              echo "Directory contents:"
              ls -la
              echo ""
              echo "Files in app directory:"
              ls -la app/ || echo "app directory not found"
              echo ""
              echo "JavaScript files:"
              find . -name "*.js" -type f | head -20
      

      # If your sonar-project.properties is at the repo root,
      # the action will pick it up automatically.
      - name: Run Sonar (SonarCloud / SonarQube)
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Optional: if you use SonarQube self-hosted, but for SonarCloud, we set SONAR_HOST_URL
          SONAR_HOST_URL: https://sonarcloud.io
