name: OWASP Dependency-Check

on:
  workflow_run:
    workflows: ["SonarCloud scan"]
    types:
      - completed

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: SCA - Dependency Vulnerability Scan
    
    steps:
      # Get the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Scan dependencies for known vulnerabilities
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'gitops-guardian-platform'
          path: './app'
          # Generate only HTML for human review and comprehendson
          format: 'HTML'
          args: >
            --enableRetired
            --enableExperimental
            --failOnCVSS 7
      
      # Upload HTML report for manual review
      - name: Upload scan report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports