name: Superlinter

on:
  workflow_run:
    workflows: ["Secret Scanning"]
    types: [completed]

  # Im adding this block because i changed my mind and i want to throw in a prior essential pipeline
  # This makes Superlinter wait until Secret Scanning passes successfully.

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Superlinter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Check if app code changed
        id: check_changes
        run: |
          # If there is no parent commit (first commit) treat as changed
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            if git diff --quiet HEAD^ HEAD -- ./app; then
              echo "No changes detected in ./app"
              echo "changes_detected=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected in ./app"
              echo "changes_detected=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No parent commit found — treating as changed"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi      

      - name: Super-linter
          # Run only if the check_changes outputs is true, meaning only if there are changes in fdoler ./app
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: super-linter/super-linter@v8 # using major version only
        continue-on-error: true
        # Continue on error, to show me my error but continue the pipeline stagings
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true  
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        # I want to upload the details to artifact logs
      - name: Upload Linter Logs 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: superlinter-logs
          path: /tmp/lint
